name: neiprax_web
description: Emotional Music Agent
version: 1.0.0+1

environment:
  sdk: '>=3.11.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Core Audio
  just_audio: ^0.9.40
  # Web Networking
  http: ^1.3.0
  # State Management (Essential for Fast Development)
  flutter_riverpod: ^2.5.1
  # UI & Animations
  animate_do: ^3.3.4
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/Sony-Logo.jpg
    - assets/images/cassette_tape.png